<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // Option A) Inline dataset (extend this array to all countries).
        $countries = [
            // name, ISO2 code, phone_code (no '+'), ISO4217, symbol
            ['name' => 'Afghanistan', 'code' => 'AF', 'phone_code' => '93',   'currency_code' => 'AFN', 'currency_sympol' => '؋'],
            ['name' => 'Albania',                  'code' => 'AL', 'phone_code' => '355',  'currency_code' => 'ALL', 'currency_sympol' => 'L'],
            ['name' => 'Algeria',                  'code' => 'DZ', 'phone_code' => '213',  'currency_code' => 'DZD', 'currency_sympol' => 'د.ج'],
            ['name' => 'Andorra',                  'code' => 'AD', 'phone_code' => '376',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Angola',                   'code' => 'AO', 'phone_code' => '244',  'currency_code' => 'AOA', 'currency_sympol' => 'Kz'],
            ['name' => 'Argentina',                'code' => 'AR', 'phone_code' => '54',   'currency_code' => 'ARS', 'currency_sympol' => '$'],
            ['name' => 'Armenia',                  'code' => 'AM', 'phone_code' => '374',  'currency_code' => 'AMD', 'currency_sympol' => '֏'],
            ['name' => 'Australia',                'code' => 'AU', 'phone_code' => '61',   'currency_code' => 'AUD', 'currency_sympol' => 'A$'],
            ['name' => 'Austria',                  'code' => 'AT', 'phone_code' => '43',   'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Azerbaijan',               'code' => 'AZ', 'phone_code' => '994',  'currency_code' => 'AZN', 'currency_sympol' => '₼'],
            ['name' => 'Bahrain',                  'code' => 'BH', 'phone_code' => '973',  'currency_code' => 'BHD', 'currency_sympol' => '.د.ب'],
            ['name' => 'Bangladesh',               'code' => 'BD', 'phone_code' => '880',  'currency_code' => 'BDT', 'currency_sympol' => '৳'],
            ['name' => 'Belarus',                  'code' => 'BY', 'phone_code' => '375',  'currency_code' => 'BYN', 'currency_sympol' => 'Br'],
            ['name' => 'Belgium',                  'code' => 'BE', 'phone_code' => '32',   'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Belize',                   'code' => 'BZ', 'phone_code' => '501',  'currency_code' => 'BZD', 'currency_sympol' => 'BZ$'],
            ['name' => 'Benin',                    'code' => 'BJ', 'phone_code' => '229',  'currency_code' => 'XOF', 'currency_sympol' => 'CFA'],
            ['name' => 'Bhutan',                   'code' => 'BT', 'phone_code' => '975',  'currency_code' => 'BTN', 'currency_sympol' => 'Nu.'],
            ['name' => 'Bolivia',                  'code' => 'BO', 'phone_code' => '591',  'currency_code' => 'BOB', 'currency_sympol' => 'Bs.'],
            ['name' => 'Bosnia and Herzegovina',   'code' => 'BA', 'phone_code' => '387',  'currency_code' => 'BAM', 'currency_sympol' => 'KM'],
            ['name' => 'Botswana',                 'code' => 'BW', 'phone_code' => '267',  'currency_code' => 'BWP', 'currency_sympol' => 'P'],
            ['name' => 'Brazil',                   'code' => 'BR', 'phone_code' => '55',   'currency_code' => 'BRL', 'currency_sympol' => 'R$'],
            ['name' => 'Brunei',                   'code' => 'BN', 'phone_code' => '673',  'currency_code' => 'BND', 'currency_sympol' => 'B$'],
            ['name' => 'Bulgaria',                 'code' => 'BG', 'phone_code' => '359',  'currency_code' => 'BGN', 'currency_sympol' => 'лв'],
            ['name' => 'Burkina Faso',             'code' => 'BF', 'phone_code' => '226',  'currency_code' => 'XOF', 'currency_sympol' => 'CFA'],
            ['name' => 'Burundi',                  'code' => 'BI', 'phone_code' => '257',  'currency_code' => 'BIF', 'currency_sympol' => 'FBu'],
            ['name' => 'Cambodia',                 'code' => 'KH', 'phone_code' => '855',  'currency_code' => 'KHR', 'currency_sympol' => '៛'],
            ['name' => 'Cameroon',                 'code' => 'CM', 'phone_code' => '237',  'currency_code' => 'XAF', 'currency_sympol' => 'FCFA'],
            ['name' => 'Canada',                   'code' => 'CA', 'phone_code' => '1',    'currency_code' => 'CAD', 'currency_sympol' => 'C$'],
            ['name' => 'Cape Verde',               'code' => 'CV', 'phone_code' => '238',  'currency_code' => 'CVE', 'currency_sympol' => '$'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'phone_code' => '236',  'currency_code' => 'XAF', 'currency_sympol' => 'FCFA'],
            ['name' => 'Chad',                     'code' => 'TD', 'phone_code' => '235',  'currency_code' => 'XAF', 'currency_sympol' => 'FCFA'],
            ['name' => 'Chile',                    'code' => 'CL', 'phone_code' => '56',   'currency_code' => 'CLP', 'currency_sympol' => '$'],
            ['name' => 'China',                    'code' => 'CN', 'phone_code' => '86',   'currency_code' => 'CNY', 'currency_sympol' => '¥'],
            ['name' => 'Colombia',                 'code' => 'CO', 'phone_code' => '57',   'currency_code' => 'COP', 'currency_sympol' => '$'],
            ['name' => 'Comoros',                  'code' => 'KM', 'phone_code' => '269',  'currency_code' => 'KMF', 'currency_sympol' => 'CF'],
            ['name' => 'Congo (Congo-Brazzaville)','code' => 'CG', 'phone_code' => '242',  'currency_code' => 'XAF', 'currency_sympol' => 'FCFA'],
            ['name' => 'Congo (DRC)',              'code' => 'CD', 'phone_code' => '243',  'currency_code' => 'CDF', 'currency_sympol' => 'FC'],
            ['name' => 'Costa Rica',               'code' => 'CR', 'phone_code' => '506',  'currency_code' => 'CRC', 'currency_sympol' => '₡'],
            ['name' => 'Côte d’Ivoire',            'code' => 'CI', 'phone_code' => '225',  'currency_code' => 'XOF', 'currency_sympol' => 'CFA'],
            ['name' => 'Croatia',                  'code' => 'HR', 'phone_code' => '385',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Cuba',                     'code' => 'CU', 'phone_code' => '53',   'currency_code' => 'CUP', 'currency_sympol' => '$'],
            ['name' => 'Cyprus',                   'code' => 'CY', 'phone_code' => '357',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Czechia',                  'code' => 'CZ', 'phone_code' => '420',  'currency_code' => 'CZK', 'currency_sympol' => 'Kč'],
            ['name' => 'Denmark',                  'code' => 'DK', 'phone_code' => '45',   'currency_code' => 'DKK', 'currency_sympol' => 'kr'],
            ['name' => 'Djibouti',                 'code' => 'DJ', 'phone_code' => '253',  'currency_code' => 'DJF', 'currency_sympol' => 'Fdj'],
            ['name' => 'Dominica',                 'code' => 'DM', 'phone_code' => '1767', 'currency_code' => 'XCD', 'currency_sympol' => '$'],
            ['name' => 'Dominican Republic',       'code' => 'DO', 'phone_code' => '1',    'currency_code' => 'DOP', 'currency_sympol' => 'RD$'],
            ['name' => 'Ecuador',                  'code' => 'EC', 'phone_code' => '593',  'currency_code' => 'USD', 'currency_sympol' => '$'],
            ['name' => 'Egypt',                    'code' => 'EG', 'phone_code' => '20',   'currency_code' => 'EGP', 'currency_sympol' => 'E£'],
            ['name' => 'El Salvador',              'code' => 'SV', 'phone_code' => '503',  'currency_code' => 'USD', 'currency_sympol' => '$'],
            ['name' => 'Equatorial Guinea',        'code' => 'GQ', 'phone_code' => '240',  'currency_code' => 'XAF', 'currency_sympol' => 'FCFA'],
            ['name' => 'Eritrea',                  'code' => 'ER', 'phone_code' => '291',  'currency_code' => 'ERN', 'currency_sympol' => 'Nkf'],
            ['name' => 'Estonia',                  'code' => 'EE', 'phone_code' => '372',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Eswatini',                 'code' => 'SZ', 'phone_code' => '268',  'currency_code' => 'SZL', 'currency_sympol' => 'E'],
            ['name' => 'Ethiopia',                 'code' => 'ET', 'phone_code' => '251',  'currency_code' => 'ETB', 'currency_sympol' => 'Br'],
            ['name' => 'Fiji',                     'code' => 'FJ', 'phone_code' => '679',  'currency_code' => 'FJD', 'currency_sympol' => '$'],
            ['name' => 'Finland',                  'code' => 'FI', 'phone_code' => '358',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'France',                   'code' => 'FR', 'phone_code' => '33',   'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Gabon',                    'code' => 'GA', 'phone_code' => '241',  'currency_code' => 'XAF', 'currency_sympol' => 'FCFA'],
            ['name' => 'Gambia',                   'code' => 'GM', 'phone_code' => '220',  'currency_code' => 'GMD', 'currency_sympol' => 'D'],
            ['name' => 'Georgia',                  'code' => 'GE', 'phone_code' => '995',  'currency_code' => 'GEL', 'currency_sympol' => '₾'],
            ['name' => 'Germany',                  'code' => 'DE', 'phone_code' => '49',   'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Ghana',                    'code' => 'GH', 'phone_code' => '233',  'currency_code' => 'GHS', 'currency_sympol' => '₵'],
            ['name' => 'Greece',                   'code' => 'GR', 'phone_code' => '30',   'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Guatemala',                'code' => 'GT', 'phone_code' => '502',  'currency_code' => 'GTQ', 'currency_sympol' => 'Q'],
            ['name' => 'Guinea',                   'code' => 'GN', 'phone_code' => '224',  'currency_code' => 'GNF', 'currency_sympol' => 'FG'],
            ['name' => 'Guinea-Bissau',            'code' => 'GW', 'phone_code' => '245',  'currency_code' => 'XOF', 'currency_sympol' => 'CFA'],
            ['name' => 'Guyana',                   'code' => 'GY', 'phone_code' => '592',  'currency_code' => 'GYD', 'currency_sympol' => '$'],
            ['name' => 'Haiti',                    'code' => 'HT', 'phone_code' => '509',  'currency_code' => 'HTG', 'currency_sympol' => 'G'],
            ['name' => 'Honduras',                 'code' => 'HN', 'phone_code' => '504',  'currency_code' => 'HNL', 'currency_sympol' => 'L'],
            ['name' => 'Hungary',                  'code' => 'HU', 'phone_code' => '36',   'currency_code' => 'HUF', 'currency_sympol' => 'Ft'],
            ['name' => 'Iceland',                  'code' => 'IS', 'phone_code' => '354',  'currency_code' => 'ISK', 'currency_sympol' => 'kr'],
            ['name' => 'India',                    'code' => 'IN', 'phone_code' => '91',   'currency_code' => 'INR', 'currency_sympol' => '₹'],
            ['name' => 'Indonesia',                'code' => 'ID', 'phone_code' => '62',   'currency_code' => 'IDR', 'currency_sympol' => 'Rp'],
            ['name' => 'Iran',                     'code' => 'IR', 'phone_code' => '98',   'currency_code' => 'IRR', 'currency_sympol' => '﷼'],
            ['name' => 'Iraq',                     'code' => 'IQ', 'phone_code' => '964',  'currency_code' => 'IQD', 'currency_sympol' => 'ع.د'],
            ['name' => 'Ireland',                  'code' => 'IE', 'phone_code' => '353',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Israel',                   'code' => 'IL', 'phone_code' => '972',  'currency_code' => 'ILS', 'currency_sympol' => '₪'],
            ['name' => 'Italy',                    'code' => 'IT', 'phone_code' => '39',   'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Jamaica',                  'code' => 'JM', 'phone_code' => '1',    'currency_code' => 'JMD', 'currency_sympol' => 'J$'],
            ['name' => 'Japan',                    'code' => 'JP', 'phone_code' => '81',   'currency_code' => 'JPY', 'currency_sympol' => '¥'],
            ['name' => 'Jordan',                   'code' => 'JO', 'phone_code' => '962',  'currency_code' => 'JOD', 'currency_sympol' => 'د.ا'],
            ['name' => 'Kazakhstan',               'code' => 'KZ', 'phone_code' => '7',    'currency_code' => 'KZT', 'currency_sympol' => '₸'],
            ['name' => 'Kenya',                    'code' => 'KE', 'phone_code' => '254',  'currency_code' => 'KES', 'currency_sympol' => 'KSh'],
            ['name' => 'Kuwait',                   'code' => 'KW', 'phone_code' => '965',  'currency_code' => 'KWD', 'currency_sympol' => 'د.ك'],
            ['name' => 'Kyrgyzstan',               'code' => 'KG', 'phone_code' => '996',  'currency_code' => 'KGS', 'currency_sympol' => ' сом'],
            ['name' => 'Laos',                     'code' => 'LA', 'phone_code' => '856',  'currency_code' => 'LAK', 'currency_sympol' => '₭'],
            ['name' => 'Latvia',                   'code' => 'LV', 'phone_code' => '371',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Lebanon',                  'code' => 'LB', 'phone_code' => '961',  'currency_code' => 'LBP', 'currency_sympol' => 'ل.ل'],
            ['name' => 'Liberia',                  'code' => 'LR', 'phone_code' => '231',  'currency_code' => 'LRD', 'currency_sympol' => '$'],
            ['name' => 'Libya',                    'code' => 'LY', 'phone_code' => '218',  'currency_code' => 'LYD', 'currency_sympol' => 'ل.د'],
            ['name' => 'Liechtenstein',            'code' => 'LI', 'phone_code' => '423',  'currency_code' => 'CHF', 'currency_sympol' => 'CHF'],
            ['name' => 'Lithuania',                'code' => 'LT', 'phone_code' => '370',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Luxembourg',               'code' => 'LU', 'phone_code' => '352',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Madagascar',               'code' => 'MG', 'phone_code' => '261',  'currency_code' => 'MGA', 'currency_sympol' => 'Ar'],
            ['name' => 'Malawi',                   'code' => 'MW', 'phone_code' => '265',  'currency_code' => 'MWK', 'currency_sympol' => 'MK'],
            ['name' => 'Malaysia',                 'code' => 'MY', 'phone_code' => '60',   'currency_code' => 'MYR', 'currency_sympol' => 'RM'],
            ['name' => 'Maldives',                 'code' => 'MV', 'phone_code' => '960',  'currency_code' => 'MVR', 'currency_sympol' => 'Rf'],
            ['name' => 'Mali',                     'code' => 'ML', 'phone_code' => '223',  'currency_code' => 'XOF', 'currency_sympol' => 'CFA'],
            ['name' => 'Malta',                    'code' => 'MT', 'phone_code' => '356',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Mauritania',               'code' => 'MR', 'phone_code' => '222',  'currency_code' => 'MRU', 'currency_sympol' => 'UM'],
            ['name' => 'Mauritius',                'code' => 'MU', 'phone_code' => '230',  'currency_code' => 'MUR', 'currency_sympol' => '₨'],
            ['name' => 'Mexico',                   'code' => 'MX', 'phone_code' => '52',   'currency_code' => 'MXN', 'currency_sympol' => '$'],
            ['name' => 'Moldova',                  'code' => 'MD', 'phone_code' => '373',  'currency_code' => 'MDL', 'currency_sympol' => 'L'],
            ['name' => 'Mongolia',                 'code' => 'MN', 'phone_code' => '976',  'currency_code' => 'MNT', 'currency_sympol' => '₮'],
            ['name' => 'Montenegro',               'code' => 'ME', 'phone_code' => '382',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Morocco',                  'code' => 'MA', 'phone_code' => '212',  'currency_code' => 'MAD', 'currency_sympol' => 'د.م.'],
            ['name' => 'Mozambique',               'code' => 'MZ', 'phone_code' => '258',  'currency_code' => 'MZN', 'currency_sympol' => 'MT'],
            ['name' => 'Myanmar',                  'code' => 'MM', 'phone_code' => '95',   'currency_code' => 'MMK', 'currency_sympol' => 'K'],
            ['name' => 'Namibia',                  'code' => 'NA', 'phone_code' => '264',  'currency_code' => 'NAD', 'currency_sympol' => '$'],
            ['name' => 'Nepal',                    'code' => 'NP', 'phone_code' => '977',  'currency_code' => 'NPR', 'currency_sympol' => '₨'],
            ['name' => 'Netherlands',              'code' => 'NL', 'phone_code' => '31',   'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'New Zealand',              'code' => 'NZ', 'phone_code' => '64',   'currency_code' => 'NZD', 'currency_sympol' => 'NZ$'],
            ['name' => 'Nicaragua',                'code' => 'NI', 'phone_code' => '505',  'currency_code' => 'NIO', 'currency_sympol' => 'C$'],
            ['name' => 'Niger',                    'code' => 'NE', 'phone_code' => '227',  'currency_code' => 'XOF', 'currency_sympol' => 'CFA'],
            ['name' => 'Nigeria',                  'code' => 'NG', 'phone_code' => '234',  'currency_code' => 'NGN', 'currency_sympol' => '₦'],
            ['name' => 'North Macedonia',          'code' => 'MK', 'phone_code' => '389',  'currency_code' => 'MKD', 'currency_sympol' => 'ден'],
            ['name' => 'Norway',                   'code' => 'NO', 'phone_code' => '47',   'currency_code' => 'NOK', 'currency_sympol' => 'kr'],
            ['name' => 'Oman',                     'code' => 'OM', 'phone_code' => '968',  'currency_code' => 'OMR', 'currency_sympol' => 'ر.ع.'],
            ['name' => 'Pakistan',                 'code' => 'PK', 'phone_code' => '92',   'currency_code' => 'PKR', 'currency_sympol' => '₨'],
            ['name' => 'Panama',                   'code' => 'PA', 'phone_code' => '507',  'currency_code' => 'PAB', 'currency_sympol' => 'B/.'],
            ['name' => 'Papua New Guinea',         'code' => 'PG', 'phone_code' => '675',  'currency_code' => 'PGK', 'currency_sympol' => 'K'],
            ['name' => 'Paraguay',                 'code' => 'PY', 'phone_code' => '595',  'currency_code' => 'PYG', 'currency_sympol' => '₲'],
            ['name' => 'Peru',                     'code' => 'PE', 'phone_code' => '51',   'currency_code' => 'PEN', 'currency_sympol' => 'S/'],
            ['name' => 'Philippines',              'code' => 'PH', 'phone_code' => '63',   'currency_code' => 'PHP', 'currency_sympol' => '₱'],
            ['name' => 'Poland',                   'code' => 'PL', 'phone_code' => '48',   'currency_code' => 'PLN', 'currency_sympol' => 'zł'],
            ['name' => 'Portugal',                 'code' => 'PT', 'phone_code' => '351',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Qatar',                    'code' => 'QA', 'phone_code' => '974',  'currency_code' => 'QAR', 'currency_sympol' => 'ر.ق'],
            ['name' => 'Romania',                  'code' => 'RO', 'phone_code' => '40',   'currency_code' => 'RON', 'currency_sympol' => 'lei'],
            ['name' => 'Russia',                   'code' => 'RU', 'phone_code' => '7',    'currency_code' => 'RUB', 'currency_sympol' => '₽'],
            ['name' => 'Rwanda',                   'code' => 'RW', 'phone_code' => '250',  'currency_code' => 'RWF', 'currency_sympol' => 'FRw'],
            ['name' => 'Saint Kitts and Nevis',    'code' => 'KN', 'phone_code' => '1869','currency_code' => 'XCD', 'currency_sympol' => '$'],
            ['name' => 'Saint Lucia',              'code' => 'LC', 'phone_code' => '1758','currency_code' => 'XCD', 'currency_sympol' => '$'],
            ['name' => 'Saint Vincent and the Grenadines','code'=>'VC','phone_code'=>'1784','currency_code'=>'XCD','currency_sympol'=>'$'],
            ['name' => 'Samoa',                    'code' => 'WS', 'phone_code' => '685',  'currency_code' => 'WST', 'currency_sympol' => 'T'],
            ['name' => 'San Marino',               'code' => 'SM', 'phone_code' => '378',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'São Tomé and Príncipe',    'code' => 'ST', 'phone_code' => '239',  'currency_code' => 'STN', 'currency_sympol' => 'Db'],
            ['name' => 'Saudi Arabia',             'code' => 'SA', 'phone_code' => '966',  'currency_code' => 'SAR', 'currency_sympol' => 'ر.س'],
            ['name' => 'Senegal',                  'code' => 'SN', 'phone_code' => '221',  'currency_code' => 'XOF', 'currency_sympol' => 'CFA'],
            ['name' => 'Serbia',                   'code' => 'RS', 'phone_code' => '381',  'currency_code' => 'RSD', 'currency_sympol' => 'din'],
            ['name' => 'Seychelles',               'code' => 'SC', 'phone_code' => '248',  'currency_code' => 'SCR', 'currency_sympol' => '₨'],
            ['name' => 'Sierra Leone',             'code' => 'SL', 'phone_code' => '232',  'currency_code' => 'SLE', 'currency_sympol' => 'Le'],
            ['name' => 'Singapore',                'code' => 'SG', 'phone_code' => '65',   'currency_code' => 'SGD', 'currency_sympol' => 'S$'],
            ['name' => 'Slovakia',                 'code' => 'SK', 'phone_code' => '421',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Slovenia',                 'code' => 'SI', 'phone_code' => '386',  'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Somalia',                  'code' => 'SO', 'phone_code' => '252',  'currency_code' => 'SOS', 'currency_sympol' => 'S'],
            ['name' => 'South Africa',             'code' => 'ZA', 'phone_code' => '27',   'currency_code' => 'ZAR', 'currency_sympol' => 'R'],
            ['name' => 'South Korea',              'code' => 'KR', 'phone_code' => '82',   'currency_code' => 'KRW', 'currency_sympol' => '₩'],
            ['name' => 'South Sudan',              'code' => 'SS', 'phone_code' => '211',  'currency_code' => 'SSP', 'currency_sympol' => '£'],
            ['name' => 'Spain',                    'code' => 'ES', 'phone_code' => '34',   'currency_code' => 'EUR', 'currency_sympol' => '€'],
            ['name' => 'Sri Lanka',                'code' => 'LK', 'phone_code' => '94',   'currency_code' => 'LKR', 'currency_sympol' => 'Rs'],
            ['name' => 'Sudan',                    'code' => 'SD', 'phone_code' => '249',  'currency_code' => 'SDG', 'currency_sympol' => '£'],
            ['name' => 'Suriname',                 'code' => 'SR', 'phone_code' => '597',  'currency_code' => 'SRD', 'currency_sympol' => '$'],
            ['name' => 'Sweden',                   'code' => 'SE', 'phone_code' => '46',   'currency_code' => 'SEK', 'currency_sympol' => 'kr'],
            ['name' => 'Switzerland',              'code' => 'CH', 'phone_code' => '41',   'currency_code' => 'CHF', 'currency_sympol' => 'CHF'],
            ['name' => 'Syria',                    'code' => 'SY', 'phone_code' => '963',  'currency_code' => 'SYP', 'currency_sympol' => '£S'],
            ['name' => 'Taiwan',                   'code' => 'TW', 'phone_code' => '886',  'currency_code' => 'TWD', 'currency_sympol' => 'NT$'],
            ['name' => 'Tajikistan',               'code' => 'TJ', 'phone_code' => '992',  'currency_code' => 'TJS', 'currency_sympol' => 'SM'],
            ['name' => 'Tanzania',                 'code' => 'TZ', 'phone_code' => '255',  'currency_code' => 'TZS', 'currency_sympol' => 'TSh'],
            ['name' => 'Thailand',                 'code' => 'TH', 'phone_code' => '66',   'currency_code' => 'THB', 'currency_sympol' => '฿'],
            ['name' => 'Togo',                     'code' => 'TG', 'phone_code' => '228',  'currency_code' => 'XOF', 'currency_sympol' => 'CFA'],
            ['name' => 'Tonga',                    'code' => 'TO', 'phone_code' => '676',  'currency_code' => 'TOP', 'currency_sympol' => 'T$'],
            ['name' => 'Trinidad and Tobago',      'code' => 'TT', 'phone_code' => '1',    'currency_code' => 'TTD', 'currency_sympol' => 'TT$'],
            ['name' => 'Tunisia',                  'code' => 'TN', 'phone_code' => '216',  'currency_code' => 'TND', 'currency_sympol' => 'د.ت'],
            ['name' => 'Türkiye',                  'code' => 'TR', 'phone_code' => '90',   'currency_code' => 'TRY', 'currency_sympol' => '₺'],
            ['name' => 'Turkmenistan',             'code' => 'TM', 'phone_code' => '993',  'currency_code' => 'TMT', 'currency_sympol' => 'm'],
            ['name' => 'Uganda',                   'code' => 'UG', 'phone_code' => '256',  'currency_code' => 'UGX', 'currency_sympol' => 'USh'],
            ['name' => 'Ukraine',                  'code' => 'UA', 'phone_code' => '380',  'currency_code' => 'UAH', 'currency_sympol' => '₴'],
            ['name' => 'United Arab Emirates',     'code' => 'AE', 'phone_code' => '971',  'currency_code' => 'AED', 'currency_sympol' => 'د.إ'],
            ['name' => 'United Kingdom',           'code' => 'GB', 'phone_code' => '44',   'currency_code' => 'GBP', 'currency_sympol' => '£'],
            ['name' => 'United States',            'code' => 'US', 'phone_code' => '1',    'currency_code' => 'USD', 'currency_sympol' => '$'],
            ['name' => 'Uruguay',                  'code' => 'UY', 'phone_code' => '598',  'currency_code' => 'UYU', 'currency_sympol' => '$U'],
            ['name' => 'Uzbekistan',               'code' => 'UZ', 'phone_code' => '998',  'currency_code' => 'UZS', 'currency_sympol' => 'soʻm'],
            ['name' => 'Vanuatu',                  'code' => 'VU', 'phone_code' => '678',  'currency_code' => 'VUV', 'currency_sympol' => 'VT'],
            ['name' => 'Venezuela',                'code' => 'VE', 'phone_code' => '58',   'currency_code' => 'VES', 'currency_sympol' => 'Bs.'],
            ['name' => 'Vietnam',                  'code' => 'VN', 'phone_code' => '84',   'currency_code' => 'VND', 'currency_sympol' => '₫'],
            ['name' => 'Yemen',                    'code' => 'YE', 'phone_code' => '967',  'currency_code' => 'YER', 'currency_sympol' => '﷼'],
            ['name' => 'Zambia',                   'code' => 'ZM', 'phone_code' => '260',  'currency_code' => 'ZMW', 'currency_sympol' => 'ZK'],
            ['name' => 'Zimbabwe',                 'code' => 'ZW', 'phone_code' => '263',  'currency_code' => 'ZWL', 'currency_sympol' => 'Z$'],
            // --- Add remaining countries/territories in the same shape ---
        ];

        // Option B) Load from JSON file (paste full list into database/seeders/data/countries.json)
        // $countries = json_decode(file_get_contents(database_path('seeders/data/countries.json')), true);

        // Normalize & add timestamps
        $countries = array_map(function ($c) use ($now) {
            return [
                'name'            => $c['name'],
                'code'            => strtoupper($c['code']),
                'phone_code'      => (string) $c['phone_code'],
                'currency_code'   => $c['currency_code'] ?? null,
                'currency_sympol' => $c['currency_sympol'] ?? null,
                'created_at'      => $now,
                'updated_at'      => $now,
            ];
        }, $countries);

        // Upsert by ISO2 code to avoid duplicates on re-seed
        DB::table('countries')->upsert(
            $countries,
            ['code'],
            ['name', 'phone_code', 'currency_code', 'currency_sympol', 'updated_at']
        );
    }
}
